[Mono.CSharp] Fix compilation for the monotouch profile with new exception filter support in mcs.
Otherwise this happens:

    MCS     [monotouch] Mono.CSharp.dll
    ../../mcs/codegen.cs(294,7): error CS1061: Type `System.Reflection.Emit.ILGenerator' does not contain
    a definition for `BeginExceptFilterBlock' and no extension method `BeginExceptFilterBlock' of
    type `System.Reflection.Emit.ILGenerator' could be found. Are you missing an assembly reference?