[ci] Use a shell script to reset HEAD for submodules
Work around a weird bug in Homebrew git 2.22.0:

    git submodule foreach --recursive git reset --hard HEAD

errors out with:

    error: unknown option `hard'
    usage: git submodule--helper foreach [--quiet] [--recursive] [--] <command>

which is nonsense because `git foreach -h` says:

    usage:
       ...
       or: git submodule [--quiet] foreach [--recursive] <command>

The workaround is to call

    git submodule foreach --recursive scripts/ci/git-reset-hard.sh HEAD

and hide the `--hard` option in the shell script