Fixing large file support compile-time check.
Previous check did not follow the same conventions for the function body as other AC_TRY_COMPILE checks. This resulted in incorrectly reporting that the system did not have large file support due to the following errors reported in config.log:

conftest.c:88: warning: function declaration isn't a prototype
conftest.c: In function 'main':
conftest.c:94: error: nested functions are disabled, use -fnested-functions to re-enable
conftest.c:94: warning: 'main' is normally a non-static function
configure:21041: $? = 1