Revert "[mcs] Adds parser support for C# 7.2 readonly references"
This reverts commit 178a49de7bfb5f53bfa4cf6914f75a8b0e886a4e.

On Linux x86_64 4.14.27-1, this commit makes the following failure occur:

```
Mono.Configuration.Crypto/Key.cs(17,22): warning CS0169: The field 'Key.keypair' is never used
CSC     [net_4_x-linux] mdbrebase.exe
CSC     [net_4_x-linux] mdb2ppdb.exe
CSC     [net_4_x-linux] mono-configuration-crypto.exe
CSC     [net_4_x-linux] ikdasm.exe
CSC     [net_4_x-linux] illinkanalyzer.exe
CSC     [net_4_x-linux] mono-symbolicate.exe
/home/akyte/mono_debugger/external/ikdasm/Disassembler.cs(2259,26): warning CS0618: 'SecurityAction.RequestMinimum' is obsolete: 'This requests should not be used'
/home/akyte/mono_debugger/external/ikdasm/Disassembler.cs(2262,26): warning CS0618: 'SecurityAction.RequestRefuse' is obsolete: 'This requests should not be used'
/home/akyte/mono_debugger/external/ikdasm/Disassembler.cs(2265,26): warning CS0618: 'SecurityAction.RequestOptional' is obsolete: 'This requests should not be used'
CSC     [net_4_x-linux] mcs.exe
cs-tokenizer.cs(926,18): error CS0117: 'Token' does not contain a definition for 'REF_PARTIAL'
make[7]: *** [../build/executable.make:142: ../class/lib/net_4_x-linux/mcs.exe] Error 1
make[6]: *** [../build/rules.make:211: do-all] Error 2
make[5]: *** [build/rules.make:232: all-recursive] Error 1
make[4]: *** [Makefile:54: profile-do--net_4_x--all] Error 2
```