[cxx] various fixes in mono/metadata (#9815)
* console-unix.c:221:21: error: cannot initialize a variable of type 'MonoMethod *' (aka '_MonoMethod *') with an rvalue of type 'gpointer' (aka 'void *')
        static MonoMethod *System_Console_DoConsoleCancelEventBackground_method = ((gpointer)-1);
                           ^                                                      ~~~~~~~~~~~~~~

* ../../mono/metadata/opcodes.h:27:14: error: ISO C++ forbids forward references to 'enum' types
typedef enum _MonoOpcodeEnum MonoOpcodeEnum;

* w32socket-unix.c:601:9: error: no matching function for call to 'mono_w32socket_send'
                ret = mono_w32socket_send (((MonoFDHandle*) sockethandle)->fd, buffers->Head, buffers->HeadLength, 0, FALSE);

Change parameter from char* to void*.

* In file included from console-unix.c:479:2: error: no matching function for call to 'set_control_chars'
        set_control_chars (MONO_ARRAY_HANDLE_PIN (control_chars_arr, gchar, 0, &h), mono_attr.c_cc);
        ^~~~~~~~~~~~~~~~~
             ^
console-unix.c:362:1: note: candidate function not viable: cannot convert argument of incomplete type 'gpointer' (aka 'void *') to 'gchar *' (aka 'char *') for 1st argument
set_control_chars (gchar *control_chars, const guchar *cc)

add cast in MONO_ARRAY_HANDLE_PIN

* w32socket-unix.c:635:11: error: assigning to 'gchar *' (aka 'char *') from incompatible type 'gpointer' (aka 'void *')
        buffer = g_malloc (SF_BUFFER_SIZE);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~

Change buffer to gpointer, and another similar.

* w32socket-unix.c:1136:99: error: cannot initialize a member subobject of type 'gpointer' (aka 'void *') with an lvalue of type 'gboolean (SOCKET, OVERLAPPED *, guint32, guint32)' (aka 'int (int, OVERLAPPED *, unsigned int, unsigned int)')
        { {0x7fda2e11,0x8630,0x436f,{0xa0,0x31,0xf5,0x36,0xa6,0xee,0xc1,0x57}} /* WSAID_DISCONNECTEX */, extension_disconect },
                                                                                                         ^~~~~~~~~~~~~~~~~~~
w32socket-unix.c:1137:99: error: cannot initialize a member subobject of type 'gpointer' (aka 'void *') with an lvalue of type 'gboolean (SOCKET, gpointer, guint32, guint32, OVERLAPPED *, TRANSMIT_FILE_BUFFERS *, guint32)' (aka 'int (int, void *, unsigned int, unsigned int, OVERLAPPED *, TRANSMIT_FILE_BUFFERS *, unsigned int)')
        { {0xb5367df0,0xcbac,0x11cf,{0x95,0xca,0x00,0x80,0x5f,0x48,0xa1,0x92}} /* WSAID_TRANSMITFILE */, extension_transmit_file },

Add cast to gpointer.
Also add const while there.

* w32process-unix.c:2189:14: error: no matching function for call to 'process_wait'
                        waitret = process_wait (process_info->process_handle, MONO_INFINITE_WAIT, NULL);

Add cast from void* to non-void*.

* w32process-unix.c:2099:3: error: cannot jump from this goto statement to its label
                goto done;
                ^
w32process-unix.c:2111:13: note: jump bypasses variable initialization
        gunichar2 *args = utf16_concat (utf16_quote, lpFile, utf16_quote, lpParameters ? utf16_space : NULL, lpParameters, (const gunichar2 *)NULL);
                   ^
w32process-unix.c:2104:19: note: jump bypasses variable initialization
        const gunichar2 *lpDirectory = coop.length.working_directory ? coop.working_directory : NULL;
                         ^
w32process-unix.c:2103:19: note: jump bypasses variable initialization
        const gunichar2 *lpParameters = coop.arguments;
                         ^
w32process-unix.c:2102:19: note: jump bypasses variable initialization
        const gunichar2 *lpFile = coop.filename;
                         ^
w32process-unix.c:2285:3: error: cannot jump from this goto statement to its label
                goto exit;
                ^
w32process-unix.c:2291:13: note: jump bypasses variable initialization
        gunichar2 *dir = coop.length.working_directory ? coop.working_directory : NULL;
                   ^
w32process-unix.c1 error generated.
:2288:13: note: jump bypasses variable initialization
        gunichar2 *args = coop.length.arguments ? coop.arguments : NULL;

etc.

Separate declaration from initialization.

* appdomain.c:554:22: note: jump bypasses variable initialization
        MonoAppDomainHandle ad = mono_domain_create_appdomain_internal (friendly_name, setup, error);
                            ^
appdomain.c:590:2: error: cannot jump from this goto statement to its label
        goto_if_nok (error, leave);
        ^
etc.

Split local declaration from initialization.

* w32process-unix.c:1914:27: error: no matching function for call to 'mono_handle_new'

and error on every typesafe MONO_HANDLE_NEW call

Have MONO_HANDLE_TYPECHECK_FOR return MonoObject* instead of gpointer, by casting.
Could probably also change mono_handle_new to accept gpointer.

* class-accessors.c:247:9: error: cannot initialize return object of type 'MonoMarshalType *' with an rvalue of type 'void *'
        return mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_MARSHAL_INFO);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:265:18: error: cannot initialize a variable of type 'Uint32Property *' with an rvalue of type 'void *'
        Uint32Property *prop = mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_REF_INFO_HANDLE);
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:273:19: error: cannot initialize a variable of type 'Uint32Property *' with an rvalue of type 'void *'
                Uint32Property *prop = mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_REF_INFO_HANDLE);
                                ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:279:18: error: cannot initialize a variable of type 'Uint32Property *' with an rvalue of type 'gpointer' (aka 'void *')
        Uint32Property *prop = mono_class_alloc (klass, sizeof (Uint32Property));
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:294:19: error: cannot initialize a variable of type 'PointerProperty *' with an rvalue of type 'gpointer' (aka 'void *')
        PointerProperty *prop = mono_class_alloc (klass, sizeof (PointerProperty));
                         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:334:9: error: cannot initialize return object of type 'MonoClassPropertyInfo *' with an rvalue of type 'void *'
        return mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_PROPERTY_INFO);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:347:9: error: cannot initialize return object of type 'MonoClassEventInfo *' with an rvalue of type 'void *'
        return mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_EVENT_INFO);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:372:18: error: cannot initialize a variable of type 'Uint32Property *' with an rvalue of type 'void *'
        Uint32Property *prop = mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_DECLSEC_FLAGS);
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:379:18: error: cannot initialize a variable of type 'Uint32Property *' with an rvalue of type 'gpointer' (aka 'void *')
        Uint32Property *prop = mono_class_alloc (klass, sizeof (Uint32Property));
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:412:18: error: cannot initialize a variable of type 'WeakBitmapData *' with an rvalue of type 'gpointer' (aka 'void *')
        WeakBitmapData *info = mono_class_alloc (klass, sizeof (WeakBitmapData));
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:423:18: error: cannot initialize a variable of type 'WeakBitmapData *' with an rvalue of type 'void *'
        WeakBitmapData *prop = mono_property_bag_get (m_class_get_infrequent_data (klass), PROP_WEAK_BITMAP);
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:454:19: error: cannot initialize a variable of type 'DimConflictData *' with an rvalue of type 'gpointer' (aka 'void *')
        DimConflictData *info = mono_class_alloc (klass, sizeof (DimConflictData));
                         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-accessors.c:469:19: error: cannot initialize a variable of type 'DimConflictData *' with an rvalue of type 'void *'
        DimConflictData *info = mono_property_bag_get (&klass->infrequent_data, PROP_DIM_CONFLICTS);
                         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cast from void* to non-void*.

* class.c:3005:16: error: assigning to 'char *' from incompatible type 'const char *'
        if ((nested = strchr (name, '/'))) {
                      ^~~~~~~~~~~~~~~~~~
class-init.c:437:11: error: assigning to 'MonoClass *' (aka '_MonoClass *') from incompatible type 'gpointer' (aka 'void *')
                klass = mono_image_alloc0 (image, sizeof (MonoClassGtd));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-init.c:442:11: error: assigning to 'MonoClass *' (aka '_MonoClass *') from incompatible type 'gpointer' (aka 'void *')
                klass = mono_image_alloc0 (image, sizeof (MonoClassDef));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class-init.c:500:5: error: cannot jump from this goto statement to its label
                                goto parent_failure;
                                ^
class-init.c:599:6: note: jump bypasses variable initialization
        int first_method_idx = cols [MONO_TYPEDEF_METHOD_LIST] - 1;
            ^
class-init.c:597:6: note: jump bypasses variable initialization
        int first_field_idx = cols [MONO_TYPEDEF_FIELD_LIST] - 1;
            ^
class-init.c:496:5: error: cannot jump from this goto statement to its label
                                goto parent_failure;
                                ^
class-init.c:599:6: note: jump bypasses variable initialization
        int first_method_idx = cols [MONO_TYPEDEF_METHOD_LIST] - 1;
            ^
class-init.c:597:6: note: jump bypasses variable initialization
        int first_field_idx = cols [MONO_TYPEDEF_FIELD_LIST] - 1;
            ^
class-init.c:490:4: error: cannot jump from this goto statement to its label
                        goto parent_failure;
                        ^
class-init.c:599:6: note: jump bypasses variable initialization
        int first_method_idx = cols [MONO_TYPEDEF_METHOD_LIST] - 1;
            ^
class-init.c:597:6: note: jump bypasses variable initialization
        int first_field_idx = cols [MONO_TYPEDEF_FIELD_LIST] - 1;
            ^
class-init.c:838:14: error: no matching function for call to 'class_kind_may_contain_generic_instances'
        image_set = class_kind_may_contain_generic_instances (eclass->class_kind) ? mono_metadata_get_image_set_for_class (eclass) : NULL;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* class.c:3005:16: error: assigning to 'char *' from incompatible type 'const char *'
        if ((nested = strchr (name, '/'))) {
                      ^~~~~~~~~~~~~~~~~~

class.c:427:10: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
                        char *s = strchr (klass_name, '`');
                              ^   ~~~~~~~~~~~~~~~~~~~~~~~~

add const, add cast, and also fix adjacent integer truncation

* assembly.c:2964:8: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
        char *eqsign = strchr (pair, '=');

add cast

* cominterop.c:664:2: error: no matching function for call to 'register_icall'
        register_icall (cominterop_get_method_interface, "cominterop_get_method_interface", "ptr ptr", FALSE);
        ^~~~~~~~~~~~~~

repeatedly

Add cast in macro.

Also another need for a cast on a string (error not recorded).

* [cxx] icall.c:
 casts
 change char* to void*
 split local declaration from initialization
 add extern "C" around external code (environ -- probably merged to master already)

* image.c:726:8: error: no matching function for call to 'strcmp'
                        if (strcmp (list_iter->data, name) == 0) {
                            ^~~~~~
image.c:1184:20: error: constant expression evaluates to 2218203019 which cannot be narrowed to type 'int' [-Wc++11-narrowing]
        IGNORED_ASSEMBLY (0x8437178B, SYS_NET_HTTP, "C0E04D9C-70CF-48A6-A179-FBFD8CE69FD0", "4.3.0 net46"),
                          ^~~~~~~~~~
 repeatedly

add casts

* [cxx] marshal.c

marshal.c:224:3: error: no matching function for call to 'register_icall'
                register_icall (mono_marshal_string_to_utf16, "mono_marshal_string_to_utf16", "ptr obj", FALSE);

repeatedly; add cast in macro

Also possible int/enum mixup -- add cast.

* [cxx] property-bag.c

property-bag.c:44:37: error: cannot initialize a variable of type 'MonoPropertyBagItem *' (aka '_MonoPropertyBagItem *') with an lvalue of type 'void *'
        MonoPropertyBagItem *cur, **prev, *item = value;

Add cast here, and another.

* [cxx] metadata.c
add casts from void* to non-void*
indicate future enum instead of int
remove designated intitializers

* [cxx] more appdomain.c

* PR: Repatriate orphaned comment.

* PR: include opcodes.h instead of duplicating MonoOpcodeEnum