Fix the build on Visual C++
Visual C++ does not support intermixed declarations and code and
errors out with:
error C2275: 'guint' : illegal use of this type as an expression

This also silences gcc/clang warnings such as:
mono-counters.c:xxx:3: warning: ISO C90 forbids mixing declarations
and code

In this case this can be fixed easily by skipping the intermediate
variable.

Based on pull request #1043 by J-M <jean-michel.perraud@csiro.au>

This change is released under the MIT license.