[cxx] Tighten up some types from void* to the correct type.
Put ves_icall_System_Environment_GetOSVersionString in a header instead
of duplicating the declaration.

[Cplusplus] Adjust types e.g. from char* to void* so that non-void* can be passed without cast.

[Cplusplus] Thread locals cannot be static on Linux? Revisit this later.

[cxx] Enums are not ints and are dealt with either by casting or providing operator overloads.
Also do not duplicate enum types, so they do not go out of sync again.

[cxx] Tentatively back off from GENERATE_BIT_ENUM_OPERATORS.

[cxx] Make mini valid C++.

[cxx] Deal with function pointers and void* and mismatched function pointer types.
Sometimes cast, sometimes change void* to the correct type.
Including rationalizing thread start -- void vs. gulong vs. gsize.

[Cplusplus] Cast away or add const on some string functions (strchr, strstr).

[Cplusplus] Do not extend or truncate between integers and pointers, always change size of integer to integer, and then pointer-sized integer and pointer.

[Cplusplus] Cast between RawHandle and ObjectHandle.

[Cplusplus] Port complex/imaginary math to C++, but hold back for Android.

[Cplusplus] Cast away overflowing integer constants.

[Cplusplus] Add some extern "C" for some of our functions that are not in any headers but have duplicated declarations.

[Cplusplus] Avoid C++ runtime dependency on math functions.
i.e. avoid the noexcept decoration that implies a runtime check and dependency.

[Cplusplus] Add extern "C" when duplicating platform headers.

[Cplusplus] fmod is overloaded, assign to local to disambiguate.

[Cplusplus] C++ does not allow copying volatile aggregates (struct, union, class).

[Cplusplus] Move mono-threads-mach-helper declarations to a file for sharing instead of duplication.

[cxx] Add casts from void* to non-void*. Change non-void* to void* (e.g. char*).

[cxx] Do not cast between pointers and non-pointer-sized integers.

fixup! [cxx] Add casts from void* to non-void*. Change non-void* to void* (e.g. char*).

Remove unreachable code.

[Cplusplus] handle void* to non-void* conversion in handle.h.
This requires some type to move across context, i.e. for
the local's type to cause a type cast.

[Cplusplus] Build system support for configure/autogen.sh -enable-cplusplus.

[Cplusplus] CentOS 6 gcc 4.4 stdint.h does not give everything without asking.

[Cplusplus] Port class-init.c to C++ again (code moved from elsewhere).
 - Cast from void* to non-void*.
 - Do not goto around initialization.
 - Enums are not ints.
 - Cast away const on some string functions (strstr).

[Cplusplus] Add casts and extern "C".

[Cplusplus] Fix integer type to avoid truncation.

[cxx] [profiler] Add casts to const mono_byte*, instead of adjusting
 the types to void* as in commit 309b3dc737ee784c3a3d9f2003e45f15b140e03d.

[Cplusplus] Better types at the mono_gc_alloc layer per https://github.com/mono/mono/pull/6695#discussion-diff-167398359L5601.

[Cplusplus] Cast repeatedly to GCVTable and GCObject* instead of overload on gpointer.

Ongoing fixups that need proper placement.

Ongoing fixups.

[cxx] handle.h work, should  fixup history more

[cxx] gpointer vs. function pointer (fixup)

mono-merp.c:83:9: error: implicit default constructor for 'MERPStruct' must explicitly initialize the const member 'systemModel'

ISO C++ forbids forward references to 'enum' types

cast from void* to non-void*

More fixes, need splitting up into separate commits later.
https://github.com/dotnet/corefx/pull/31342 also required.

Update to C++11 for CoreFX which cannot be compiled as C++98.

More C++ fixes.

Update comments about corefx

Restore accidentally lost handle cast functions.

more extern C -- and it links.

github typography

Repair file damage.

Compile NetFX/Native as C, move C++ back to C++98.

Namespace: __stdcall => MONO_STDCALL
Might also move to a less public header, might.
Space on funtion calls.

Report after bad merges.

Repair after different fixes.

Rollback some.

fixup int vs. enum

[cxx] Adapt new code for Windows/x86/C++.

[cxx] Cast from void* to nono-void*.

Add extern C.

[cxx] Make main be C, because cannot link with -xc++, it treats
the libraries as C++. Renaming main to .cpp would help a little.
Main is small so shouldn't be a big deal and be further factored if needed/wantes.

PR: For consistency, favor MONO_BEGIN_DECLS / MONO_END_DECLS in the metadata and utils directories.
Some code did not have these macros available.
Rather than the higher risk addition or movement of headers, these macros are added
in two additional headers to safely extend their reach (mono-compiler.h, glib.h; already in mono-publib.h).

Pre-existing inconsistency is not altered here.
sgen and mini consistently use G_BEGIN_DECLS / G_END_DECLS.
Aside from these macros, no un-macroed extern "C" is now added, outside of libgc.

libgc needs extern "C" to be C interoperating with C++. This tracks mainline libgc as well,
though that is probably moot.

fixup configure.ac

cxx vs. cplusplus

do not merge -- make C++ the default for this branch/PR

cplusplus vs. cxx

[cxx] 1. Favor G_BEGIN_DECLS / G_END_DECLS in non-public headers (and .c files), which is the overwhelmingly common case.
2. Use MONO_BEGIN_DECLS / MONO_END_DECLS in public headers, which are a small well defined listed (with two outliers
that include glib.h but maybe should not https://github.com/mono/mono/issues/9801).
3. use MONO_BEGIN_DECLS in non-public headers if G_BEGIN_DECLS is unavilable. This is very rare but occurs.
4. Use extern "C" when neither macro is available. This is very rare but occurs.
5. Continue to use extern "C" in libgc.
6. Do not add or reorder any defines or includes to achieve this, therefore point 4.
If rule 6 bends, then rule 4 and probably 3 would too.
As this is about consistency and style, rule 6 holds.

Alternatively, at a later date:
 Put extern "C" in MONO_API, and maybe ICALL_EXPORT.
   Fill in missing of each.
 Change all "extern MONO_API" to just MONO_API to prevent a warning about `extern extern "C"`.
 Empty G_BEGIN_DECLS and/or remove all of its uses

And convert glib to C++, possibly at an earlier date.

[cxx] Alternate approach to extern "C", now that most of the tree is C++ (in branch cplusplus.2).
Only use extern "C" selectively, not around all headers.
 - Fully around public headers, as MONO_BEGIN_DECLS / MONO_END_DECLS.
   That might not be done yet, but it is a relatively small task.
 - Within MONO_API, which is somewhat redundant with public headers,
   but also is in private headers for dlopen/dlsym use.
 - For monodis interop at least for now.
 - When a prototype is duplicated, in and out of public headers. At least for now.
 - To workaround the THREAD_INFO_TYPE hack at least for now.
   We declare functions one way but implement them another way.
   This should probably be gpointer instead, or overloads.

Collateral work/damage/change:
 - For icalls, add includes and prototypes.
 - Put extern "C" in MONO_API.
 - Tweak occurences of `extern` wrt MONO_API.
   Remove it on functions, where it is meaningless.
   Arrange for it to occur at most once on data, where it is meaningful,
   but where multiple occurences warn or error.

Compile more code I had missed as C++.

There is probably some excess newlines now that I have to tediously remove.

MONO_API_DATA refinement

[cxx] remove underscore in enum MonoOpcodeEnum, this should fix some linking due to different names

[cxx] support for pedump

[cxx] Put MONO_API ahead of MONO_RT_EXTERNAL_ONLY, because
gcc doesn't like exterC in between pragma, like:

Remove accidental deprecation.

[cxx] Undo the icall changes; make them extern "C" instead:
 define ICALL_EXPORT MONO_EXTERN_C

still to find missing ICALL_EXPORT.

https://github.com/mono/mono/pull/9814#discussion_r206561438

[cxx] Factor extern "C" into MONO_EXTERN_C so MONO_API isn't duplicatec.
https://github.com/mono/mono/pull/9814#discussion_r206541528

[cxx] Move define ICALL_EXPORT from class-internals.h to glib.h for greater availability.

[cxx] Add many missing ICALL_EXPORT.

[cxx] Port complex math to small portable C and C++ with the only dependency being hypot and non-complex math.
One liner cabs with alternative license remains, now on all platforms.
Granted, whatever was the libc++ dependency was probably inlined.

[cxx] handle.h use C++11 as the C++98 raised objections.

Fix assignment of volatile aggregate without raising specter of ifdef __cplusplus.
Does this violate the abstraction?

fix merge

[cxx] fix more platforms

Put MONO_API ahead of MONO_RT_EXTERNAL_ONLY -- fix gcc/Linux

More cast from void* to non-void*.

fix merge

fix merge

undo a change, see if it helps

reduce diff

temporary diff reduction

temporary diff reduction

fix merge

restore whitespace

temporary diff reduction

temporary diff reduction

temporary diff reduction

temporary diff reduction

temporary diff reduction

temporary diff reduction

diff reduction

diff reduction

diff reduction

temporary diff reduction

diff reduction

temporary diff reduction

diff reduction

diff reduction

diff reduction

temporary diff reduction

temporary diff reduction

diff reduction

temporary diff reduction

diff reduction

diff reduction

temporary diff reduction

diff reduction

temporary diff reduction

diff reduction

diff reduction

diff reduction

diff reduction

temporary? diff reduction

diff reduction

remove old complex number port

temporary diff reduction

temporary diff reduction

diff reduction

diff reduction

diff reduction

diff reduction

diff reduction

temporary diff reduction

diff reduction

diff reduction

diff reduction

temporary diff reduction

diff reduction

temporary diff reduction

Fix more configurations -- cast function pointer to void*.

Fix Windows.

temporary  workaround for monodis

fix x86

arm fixes

tighten up more types

[cxx] int vs. enum

diff reduction

more gpointer, less guint8*

more void* vs. non-void*

strengthen pointers away fram void*

int vs. enum

favor guint8* over char*

reduce diff

reduce/start-over

reduce/start-over

wip

debugger-agent.c

mini-arm64-gsharedvt.c

mini-arm64.c

tramp-x86.c

exceptions-arm64.c

mono/mini/mini-x86.c

mono/mini/tramp-arm64.c

mono/mini/tramp-arm64.c

mono/mini/tramp-arm64.c

mono/mini/exceptions-arm64.c

mono/mini/tramp-arm64-gsharedvt.c

mono/mini/exceptions-arm64.c

mono/mini/tramp-arm64-gsharedvt.c

mono/mini/exceptions-arm64.c

mono/mini/mini.h

configure.ac

mono/mini/mini-arm64.c

mono/mini/mini-arm64.c

configure.ac

attach.c

remove toplevel const, cast away integer truncation

attach.c

mono/metadata/w32file-unix.c

debug-helpers.c

gc.c

mono/arch/arm/arm-codegen.h

mono/mini/mini-arm.c

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/13143/parsed_console/log.html

```
.deps/libmonoruntime_la-domain.Tpo -c -o libmonoruntime_la-domain.lo `test -f 'domain.c' || echo './'`domain.c
appdomain.c:2493:5: error: cannot jump from this goto statement to its label
                                goto_if_nok (error, fail);
                                ^
../../mono/utils/mono-error-internals.h:118:35: note: expanded from macro 'goto_if_nok'
                                  ^
../../mono/utils/mono-error-internals.h:116:48: note: expanded from macro 'goto_if'
                                                 ^
appdomain.c:2500:14: note: jump bypasses variable initialization
        const char *basedir = NULL;
                    ^
appdomain.c:2499:26: note: jump bypasses variable initialization
        MonoAssemblyContextKind asmctx = refOnly ? MONO_ASMCTX_REFONLY : MONO_ASMCTX_DEFAULT;
                                ^
appdomain.c:2490:4: error: cannot jump from this goto statement to its label
                        goto_if_nok (error, fail);
                        ^
../../mono/utils/mono-error-internals.h:118:35: note: expanded from macro 'goto_if_nok'
                                  ^
../../mono/utils/mono-error-internals.h:116:48: note: expanded from macro 'goto_if'
                                                 ^
appdomain.c:2500:14: note: jump bypasses variable initialization
        const char *basedir = NULL;
                    ^
appdomain.c:2499:26: note: jump bypasses variable initialization
        MonoAssemblyContextKind asmctx = refOnly ? MONO_ASMCTX_REFONLY : MONO_ASMCTX_DEFAULT;
                                ^
appdomain.c:2481:2: error: cannot jump from this goto statement to its label
        goto_if_nok (error, fail);
        ^
../../mono/utils/mono-error-internals.h:118:35: note: expanded from macro 'goto_if_nok'
                                  ^
../../mono/utils/mono-error-internals.h:116:48: note: expanded from macro 'goto_if'
                                                 ^
appdomain.c:2500:14: note: jump bypasses variable initialization
        const char *basedir = NULL;
                    ^
appdomain.c:2499:26: note: jump bypasses variable initialization
        MonoAssemblyContextKind asmctx = refOnly ? MONO_ASMCTX_REFONLY : MONO_ASMCTX_DEFAULT;
                                ^
3 errors generated.
```

mono/mini/mini-arm.c

mono/mini/mini-arm.c

mono/mini/mini-amd64.c

add const to mono-path.c

[cxx] add extern C for

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/13150/parsed_console/log.html

```
sx/mcs/class/lib/net_4_x/System.Xml.dll -r:/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/lib/net_4_x/System.Core.dll -out:callspec.exe callspec.cs
  CCLD     test-mono-callspec
Undefined symbols for architecture x86_64:
  "_mono_class_from_name_checked", referenced from:
      _main in test_mono_callspec-test-mono-callspec.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test-mono-callspec] Error 1
  CC       test_mono_string-test-mono-string.o
  CCLD     test-mono-string
make[2]: Leaving directory `/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mono/unit-tests'

```

add some casts to mini-x86.c

add some casts to tramp-x86.c

some x86 fixes casts

x86

[cxx][jit][arm] Make ARM-specific JIT code valid C++.
Lots of casts.
One type change.
One macro rewrite.

less externC, i.e. on internals

coop stack cast

[cxx] dlmalloc..

more thread start cleanup

remove duplicate MonoInst (warning I caused)

another duplicate typedef

do not merge -- alter suspend policy

Accomodate tests written in C for now.

The lifetime is not enough for the wrapper.

Fix thread create wrapper lifetime.

another cast

some LLVM fix, more to do

Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -g -O2 -Wno-format-zero-length -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -g -mno-tls-direct-seg-refs -DDISABLE_CRASH_REPORTING=1 -xc++ -std=gnu++11 -fno-exceptions -fno-rtti -MT libmonoutils_la-mono-log-windows.lo -MD -MP -MF .deps/libmonoutils_la-mono-log-windows.Tpo -c mono-log-windows.c  -DDLL_EXPORT -DPIC -o .libs/libmonoutils_la-mono-log-windows.o
mono-log-windows.c:32:31: warning: ISO C++ forbids converting a string constant to 'wchar_t*' [-Wwrite-strings]
 static wchar_t *logFileName = L".//mono.log";
                               ^~~~~~~~~~~~~~
libtool: compile:  i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../mono -I../../libgc/include -I../../mono/eglib -I../../mono/eglib -fvisibility=hidden -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -D_WIN32_IE=0x0501 -D_UNICODE -DUNICODE -DWIN32_THREADS -DFD_SETSIZE=1024 -g -xc++ -std=gnu++11 -fno-exceptions -fno-rtti -Wall -Wunused -Wmissing-declarations -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -g -O2 -Wno-format-zero-length -fno-

add const

fix merge