Partial revert of "Fixes mobile build"
This reverts commit 4d3877d23ba88a772d2d4dacb380c02a15495e55.

We cannot remove this file as the build logic is expecting it since we override it from mono-extensions.

```System/Guid.cs(42,7): error CS0246: The type or namespace name `Crimson' could not be found. Are you missing an assembly reference?```