2004-11-26  Miguel de Icaza  <miguel@ximian.com>
	* convert.cs (ImplicitReferenceConversion): Corrected typo, I was
	testing the target_type (which was known to be object_type) and
	not the source type (which is anonymous_method).

	Fixed reporting of error cs1660.


svn path=/trunk/mcs/; revision=36658