[cxx] everything, now with less line damage
[cxx] Dial back g_cast and strcmp overload.

x86 fixes

[cxx] fix checked build

checked-build.c: In function 'mono_bool mono_check_mode_enabled(MonoCheckMode)':
checked-build.c:51:24: error: invalid conversion from 'int' to 'MonoCheckMode' [-fpermissive]
      env_check_mode |= MONO_CHECK_MODE_GC;
                        ^~~~~~~~~~~~~~~~~~
checked-build.c:59:24: error: invalid conversion from 'int' to 'MonoCheckMode' [-fpermissive]
      env_check_mode |= MONO_CHECK_MODE_THREAD;
                        ^~~~~~~~~~~~~~~~~~~~~~
checked-build.c: In function 'void checked_build_init()':
checked-build.c:115:50: error: invalid conversion from 'int' to 'MonoCheckMode' [-fpermissive]
  if (mono_check_mode_enabled (MONO_CHECK_MODE_GC | MONO_CHECK_MODE_THREAD))
                               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
checked-build.c:35:1: note:   initializing argument 1 of 'mono_bool mono_check_mode_enabled(MonoCheckMode)'
 mono_check_mode_enabled (MonoCheckMode query)
 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../mono/utils/mono-threads.h:19:0,
                 from checked-build.c:16:
checked-build.c: In function 'CheckState* get_state()':
../../mono/utils/mono-tls.h:59:59: error: invalid conversion from 'void*' to 'CheckState*' [-fpermissive]
 #define mono_native_tls_get_value(x) (pthread_getspecific (x))
                                      ~~~~~~~~~~~~~~~~~~~~~^~~~
checked-build.c:137:22: note: in expansion of macro 'mono_native_tls_get_value'
  CheckState *state = mono_native_tls_get_value (thread_status);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
checked-build.c: In function 'void checked_build_thread_transition(const char*, void*, int, int, int, int, gboolean)':
checked-build.c:291:40: error: invalid conversion from 'void*' to 'MonoThreadInfo* {aka _MonoThreadInfo*}' [-fpermissive]
  if (!mono_thread_info_is_current (info))
                                        ^
In file included from checked-build.c:16:0:
../../mono/utils/mono-threads.h:772:1: note:   initializing argument 1 of 'gboolean mono_thread_info_is_current(MonoThreadInfo*)'
 mono_thread_info_is_current (THREAD_INFO_TYPE *info);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

[cxx] LLVM fixes.

mini-llvm.c: In function 'void process_call(EmitContext*, MonoBasicBlock*, LLVMOpaqueBuilder**, MonoInst*)':
mini-llvm.c:3278:50: error: invalid conversion from 'gpointer {aka void*}' to 'LLVMValueRef {aka LLVMOpaqueValue*}' [-fpermissive]
     LLVMValueRef tramp_var = g_hash_table_lookup (ctx->jit_callees, call->method);

mini-llvm.c:5946:30: error: invalid conversion from 'gpointer {aka void*}' to 'LLVMValueRef {aka LLVMOpaqueValue*}' [-fpermissive]
    var = g_hash_table_lookup (ctx->module->objc_selector_to_var, name);

mini-llvm.c:6893:46: error: invalid conversion from 'void*' to 'void**' [-fpermissive]
  while (g_hash_table_iter_next (&iter, NULL, (gpointer)&l))
                                              ^~~~~~~~~~~~

mini-llvm.c:7560:40: error: invalid conversion from 'gpointer {aka void*}' to 'GSList* {aka _GSList*}' [-fpermissive]
    GSList *addrs = g_hash_table_lookup (domain_info->llvm_jit_callees, callee);

mini-llvm.c: In function 'void add_intrinsic(LLVMModuleRef, int)':
mini-llvm.c:8146:29: error: invalid conversion from 'gpointer {aka void*}' to 'const char*' [-fpermissive]
  name = g_hash_table_lookup (intrins_id_to_name, GINT_TO_POINTER (id));

mini-llvm.c:9335:42: error: invalid conversion from 'void*' to 'LLVMValueRef {aka LLVMOpaqueValue*}' [-fpermissive]
    loc_md = mono_llvm_di_create_location (ctx->module->di_builder, ctx->dbg_md, loc->row, loc->column);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[cxx] fix windows

  ..\mono\utils\mono-mmap-windows.c(209): error C2143: syntax error: missing ')' before '(' [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2059: syntax error: ')' [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2059: syntax error: '(' [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2143: syntax error: missing ')' before 'type' [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2091: function returns function [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2373: 'mono_file_map': redefinition; different type modifiers [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2085: 'flags': not in formal parameter list [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): error C2059: syntax error: '<parameter-list>' [d:\j\workspace\x\msvc\libmonoutils.vcxproj]
  ..\mono\utils\mono-mmap-windows.c(209): fatal error C1903: unable to recover from previous error(s); stopping compilation [d:\j\workspace\x\msvc\libmonoutils.vcxproj]

undamage

extend for hashtable lookup

Try __typeof__ for Centos6 gcc.

Use c++0x instead of c++11 for Centos6/gcc compatibility.

[cxx] g_hash_table_lookup support was too much for gcc4.4/Centos6 to fix LLVM otherwise.

   mini-llvm.c: In function 'void process_call(EmitContext*, MonoBasicBlock*, LLVMOpaqueBuilder**, MonoInst*)':
    mini-llvm.c:3278:50: error: invalid conversion from 'gpointer {aka void*}' to 'LLVMValueRef {aka LLVMOpaqueValue*}' [-fpermissive]
         LLVMValueRef tramp_var = g_hash_table_lookup (ctx->jit_callees, call->method);

    mini-llvm.c:5946:30: error: invalid conversion from 'gpointer {aka void*}' to 'LLVMValueRef {aka LLVMOpaqueValue*}' [-fpermissive]
        var = g_hash_table_lookup (ctx->module->objc_selector_to_var, name);

    mini-llvm.c:6893:46: error: invalid conversion from 'void*' to 'void**' [-fpermissive]
      while (g_hash_table_iter_next (&iter, NULL, (gpointer)&l))
                                                  ^~~~~~~~~~~~

    mini-llvm.c:7560:40: error: invalid conversion from 'gpointer {aka void*}' to 'GSList* {aka _GSList*}' [-fpermissive]
        GSList *addrs = g_hash_table_lookup (domain_info->llvm_jit_callees, callee);

    mini-llvm.c: In function 'void add_intrinsic(LLVMModuleRef, int)':
    mini-llvm.c:8146:29: error: invalid conversion from 'gpointer {aka void*}' to 'const char*' [-fpermissive]
      name = g_hash_table_lookup (intrins_id_to_name, GINT_TO_POINTER (id));

[cxx] wasm-specific fixes

https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/3570/parsed_console/log.html

/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-threads-wasm.c:133:12: error: assigning to 'guint8 *' (aka 'unsigned char *') from incompatible type 'void *'
        *staddr = (void*)wasm_get_stack_base ();
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-threads-wasm.c:172:7: error: no matching function for call to 'monoeg_g_slist_find'
        if (!g_slist_find (jobs, cb))
             ^~~~~~~~~~~~
                     ^
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/utils/mono-threads-wasm.c:173:10: error: no matching function for call to 'monoeg_g_slist_prepend'
                jobs = g_slist_prepend (jobs, cb);
                       ^~~~~~~~~~~~~~~
3 errors generated.

[cxx] gcc4.4/Centos6 does not support designated initializers

g++4.4 has no designated initialers.

[cxx] use cstdint for g++4.4 sake

[cxx] use cstdint for g++4.4 sake

wip

stdint/g++4.4

readable

[cxx] g++4.4 designated initializers

[cxx] g++4.4 designated initializers

[cxx] g++4.4 designated initializers

[cxx] g++4.4 designated initializers

g++4.4 no designated initializers

Limit g++4.4 fix.

add cast for x86

[cxx][wasm] goto around init

cstdint missing on Mac

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/13401/parsed_console/log.html

sgen-mono-ilgen.c:11:10: fatal error: 'cstdint' file not found
         ^
1 error generated.

extern "C" on check_build_init.

https://jenkins.mono-project.com/job/test-mono-pull-request-coop/6668/parsed_console/log.html

../../mono/utils/.libs/libmonoutils.a ../../mono/eglib/.libs/libeglib.a -lm -lrt -ldl -lpthread
main.o: In function `main':
/mnt/jenkins/workspace/test-mono-pull-request-coop/mono/dis/main.c:2034: undefined reference to `mono_checked_build_init'
collect2: error: ld returned 1 exit status
Makefile:594: recipe for target 'monodis' failed
make[3]: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-coop/mono/dis'

[cxx][x86] add cast

more casts

[cxx] Fix windows.

add cast for checked build

[cxx] Make gunichar2==wchar_t on Windows.
In C++ wchar_t is a unique type.
Alternative would be to cast, a lot.

[cxx] Something wrong with G_GINT32_FORMAT?

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/3784/parsed_console/log.html

gc.c:1731:44: error: expected ')'
        SGEN_LOG (1, "Start nursery collection %" G_GINT32_FORMAT " %p-%p, size: %d", mono_atomic_load_i32 (&mono_gc_stats.minor_gc_count), sgen_nursery_section->data, sgen_nursery_section->end_data, (int)(sgen_nursery_section->end_data - sgen_nursery_section->data));
                                                  ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/eglib/glib.h:273:25: note: expanded from macro 'G_GINT32_FORMAT'
                        ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/sgen/sgen-gc.c:1731:2: note: to match this '('
        SGEN_LOG (1, "Start nursery collection %" G_GINT32_FORMAT " %p-%p, size: %d", mono_atomic_load_i32 (&mono_gc_stats.minor_gc_count), sgen_nursery_section->data, sgen_nursery_section->end_data, (int)(sgen_nursery_section->end_data - sgen_nursery_section->data));
        ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/sgen/sgen-gc.h:143:3: note: expanded from macro 'SGEN_LOG'
                mono_gc_printf (sgen_gc_debug_file, "%s " format "\n", logTime, ##__VA_ARGS__); \
                ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/utils/mono-logger-internals.h:97:56: note: expanded from macro 'mono_gc_printf'
                                                       ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/sgen/sgen-gc.c:2181:42: error: expected ')'
        SGEN_LOG (1, "Start major collection %" G_GINT32_FORMAT, mono_atomic_load_i32 (&mono_gc_stats.major_gc_count));
                                                ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/eglib/glib.h:273:25: note: expanded from macro 'G_GINT32_FORMAT'
                        ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/sgen/sgen-gc.c:2181:2: note: to match this '('
        SGEN_LOG (1, "Start major collection %" G_GINT32_FORMAT, mono_atomic_load_i32 (&mono_gc_stats.major_gc_count));
        ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/sgen/sgen-gc.h:143:3: note: expanded from macro 'SGEN_LOG'
                mono_gc_printf (sgen_gc_debug_file, "%s " format "\n", logTime, ##__VA_ARGS__); \
                ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/utils/mono-logger-internals.h:97:56: note: expanded from macro 'mono_gc_printf'
                                                       ^
2 errors generated.

[cxx] add a cast for

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/3791/parsed_console/log.html
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/mini/mini-runtime.c:4481:2: error: no matching function for call to 'mono_add_internal_call'
        mono_add_internal_call ("System.Diagnostics.Debugger::Mono_UnhandledException_internal",
        ^~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mono/metadata/loader.h:59:1: note: candidate function not viable: no known conversion from 'void (*)(MonoException *)' (aka 'void (*)(_MonoException *)') to 'const void *' for 2nd argument; take the address of the

[cxx] externC for monodis and pedump

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-checked-private-types-build/4436/parsed_console/log.html

mono/dis/dump.c:901: undefined reference to `m_class_is_enumtype'
collect2: error: ld returned 1 exit status
Makefile:594: recipe for target 'monodis' failed
make[3]: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-amd64-checked-private-types-build/mono/dis'
make[3]: *** [monodis] Error 1

[cxx] externC for pedump

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-checked-private-types-build/4443/parsed_console/log.html

undefined reference to `m_class_get_name'
/mnt/jenkins/workspace/test-mono-pull-request-amd64-checked-private-types-build/tools/pedump/pedump.c:539: undefined reference to `m_class_get_name_space'
collect2: error: ld returned 1 exit status
Makefile:512: recipe for target 'pedump' failed

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-checked-private-types-build/4443/parsed_console/log.html

pedump.o: In function `dump_verify_info':
pedump.c:380: undefined reference to `m_class_get_byval_arg'
pedump.o: In function `verify_image_file':
pedump.c:530: undefined reference to `m_class_get_name'
pedump.c:530: undefined reference to `m_class_get_name_space'
pedump.c:539: undefined reference to `m_class_get_name'
pedump.c:539: undefined reference to `m_class_get_name_space'
collect2: error: ld returned 1 exit status
Makefile:512: recipe for target 'pedump' failed
make[3]: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-amd64-checked-private-types-

casts for wasm

https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/3616/parsed_console/log.html

/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini-runtime.c:3467:3: error: no matching function for call to 'mono_handle_native_crash'
                mono_handle_native_crash ("SIGSEGV", ctx, info);
                ^~~~~~~~~~~~~~~~~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini.h:2411:10: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to 'siginfo_t *' for 3rd argument
void     mono_handle_native_crash               (const char *signal, void *sigctx, MONO_SIG_HANDLER_INFO_TYPE *siginfo);
         ^
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini-runtime.c:3478:3: error: no matching function for call to 'mono_handle_native_crash'
                mono_handle_native_crash ("SIGSEGV", ctx, info);
                ^~~~~~~~~~~~~~~~~~~~~~~~
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini.h:2411:10: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to 'siginfo_t *' for 3rd argument
void     mono_handle_native_crash               (const char *signal, void *sigctx, MONO_SIG_HANDLER_INFO_TYPE *siginfo);
         ^
2 errors generated.

[cxx] fix windows

https://jenkins.mono-project.com/job/x/12693/parsed_console/log.html

gmisc-win32.c: In function 'const gchar* monoeg_g_get_home_dir()':
gmisc-win32.c:173:16: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
   g_free (drive);
                ^
In file included from ./glib.h:45:0,
                 from gmisc-win32.c:32:
./eglib-remap.h:53:16: note:   initializing argument 1 of 'void monoeg_g_free(void*)'
 #define g_free monoeg_g_free
                ^
./glib.h:286:6: note: in expansion of macro 'g_free'
 void g_free (void *ptr);
      ^~~~~~
gmisc-win32.c:174:15: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
   g_free (path);
               ^
In file included from ./glib.h:45:0,
                 from gmisc-win32.c:32:
./eglib-remap.h:53:16: note:   initializing argument 1 of 'void monoeg_g_free(void*)'
 #define g_free monoeg_g_free
                ^
./glib.h:286:6: note: in expansion of macro 'g_free'
 void g_free (void *ptr);

[cxx] fix wasm interop

externC mono_llvm_cpp_throw_exception

more casts

externC __jit_debug_register_code

[cxx] wasm: restrict and cast

cast from void*

cast for __builtin___clear_cache

[cxx] [wasm] [debugger] casts

[cxx][wasm]

wchar and wasm cast

casts

really fix wchar

reduce damage

restore some signature and comment