[Coop] Convert ves_icall_System_Environment_GetEnvironmentVariableNames. [Coop] Convert ves_icall_System_Environment_Exit. [Coop] Convert ves_icall_System_Environment_GetIs64BitOperatingSystem [Coop] Convert ves_icall_System_Environment_GetLogicalDrives [Coop] ves_icall_System_Environment_GetPageSize [Coop] ves_icall_System_Environment_InternalSetEnvironmentVariable [Coop] ves_icall_System_Environment_get_ExitCode [Coop] ves_icall_System_Environment_get_HasShutdownStarted Cleanup ves_icall_System_Environment_BroadcastSettingChange. [Coop] ves_icall_System_Environment_get_Platform. [Coop] System_Environment_get_ProcessorCount. [Coop] ves_icall_System_Environment_get_TickCount. [Coop] ves_icall_System_Environment_set_ExitCode. Remove extra layer from ves_icall_System_Environment_get_Platform. Remove layer from ves_icall_System_Environment_GetWindowsFolderPath. Remove layer from ves_icall_Microsoft_Win32_NativeMethods_WaitForInputIdle. Remove layer from ves_icall_System_Diagnostics_DefaultTraceListener_WriteWindowsDebugString (OutputDebugString). Cleanup ves_icall_System_Environment_GetLogicalDrives. [Coop] ves_icall_System_IO_DriveInfo_GetDiskFreeSpace [Coop] ves_icall_System_IO_DriveInfo_GetDriveFormat
[Coop] Dial back HANDLES() when NOHANDLES() suffices, i.e. when
there are no handles, and perhaps no error paths.

Remove almost do-nothing layer.

Move icalls from gc-internals.h to icall-decl.h due to Boehm compile error.
	O2 -m32 -arch i386 -mmacosx-version-min=10.9 -arch i386 -Wmissing-prototypes -Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -std=gnu99 -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -g -Werror-implicit-function-declaration -Werror=incompatible-pointer-types -MT libmonoruntime_la-attach.lo -MD -MP -MF .deps/libmonoruntime_la-attach.Tpo -c -o libmonoruntime_la-attach.lo `test -f 'attach.c' || echo './'`attach.c
	w32file-unix.c:4936:16: error: implicit declaration of function 'GC_dlopen' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
		libc_handle = dlopen ("/usr/lib/libc.dylib", 0);
			      ^
	../../libgc/include/gc_pthread_redirects.h:112:17: note: expanded from macro 'dlopen'
			^
	w32file-unix.c:4936:16: note: did you mean 'dlopen'?
	../../libgc/include/gc_pthread_redirects.h:112:17: note: expanded from macro 'dlopen'
			^
	/usr/include/dlfcn.h:57:15: note: 'dlopen' declared here
	extern void * dlopen(const char * __path, int __mode);
		      ^
	w32file-unix.c:4936:14: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
		libc_handle = dlopen ("/usr/lib/libc.dylib", 0);
			    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~