[2019-10] [debugger] Assert when async debug a generic method (#17788)
* When we try to call a method to get the async_id to do an async debug and we are trying to do this in a generic method like this:

async Task<T> ExecuteAsync_Broken<T>()
 {
            await Task.Delay(2);
            return default;
  }

We need to inflate the generic type before call the method or we will get the error:  Could not execute the method because the containing type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[T_REF]’, is not fully instantiated.

Fixes #17549
Fixes #17569

* Do not use reserved word "class

* adding unit test

* Update mono/mini/debugger-agent.c

Co-Authored-By: Aleksey Kliger (λgeek) <akliger@gmail.com>

* Adding mono prefix.

* Moving mono_get_generic_context_from_stack_frame to debugger-engine because debugger-agent is not used on wasm, causing a compilation error.

* Moving mono_get_generic_context_from_stack_frame back to mini-exception and the declaration is in mini.h