[cxx][wasm] test.js:150: TypeError: Module.pump_message is not a function
https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/3693/parsed_console/log.html

WASM: Regression tests: 6 ran, 0 failed in DevirtualizationTests
test.js:150: TypeError: Module.pump_message is not a function
			Module.pump_message ();
          ^
TypeError: Module.pump_message is not a function
    at test.js:150:11

Makefile:160: recipe for target 'run-v8-mini' failed