w32process-unix.c:1914:27: error: no matching function for call to 'mono_handle_new'
and error on every typesafe MONO_HANDLE_NEW call

Have MONO_HANDLE_TYPECHECK_FOR return MonoObject* instead of gpointer, by casting.
Could probably also change mono_handle_new to accept gpointer.