Revert "[xbuild] Fix building with 2.0 toolset"
This reverts commit 2086958399f30a8b7a997203c87d92dab2b507ce.

Revert this as it breaks the build:

MCS [net_2_0] Microsoft.Build.Engine.dll
Microsoft.Build.BuildEngine/Engine.cs(114,81): error CS0117: Microsoft.Build.Utilities.TargetDotNetFrameworkVersion' does not contain a definition forVersion30'
/root/my-mono-fork/mcs/class/Microsoft.Build.Engine/./../../class/lib/net_2_0/Microsoft.Build.Utilities.dll (Location of the symbol related to previous error)
Microsoft.Build.BuildEngine/Engine.cs(116,81): error CS0117: Microsoft.Build.Utilities.TargetDotNetFrameworkVersion' does not contain a definition forVersion35'
/root/my-mono-fork/mcs/class/Microsoft.Build.Engine/./../../class/lib/net_2_0/Microsoft.Build.Utilities.dll (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 0 warnings