Fix pointer truncation errors in cross build.
Cast pointers to gsize or gssize, which match a host pointer, not target. (mgreg_t is signed, so gssize there).
Note that these code paths are are dead and could be assert unreachable under cross compile, or
ifndef cross compiled away. However, keeping the code in, gives the cross compiler the better hope
of some day also being a native JIT (multi-arch/multi-configure).

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/26/parsed_console/log.html

/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/method-to-ir.c:3609:4: error: cast from pointer to smaller type 'target_mgreg_t' (aka 'int') loses information
                        MONO_EMIT_NEW_BIALU_IMM (cfg, OP_COMPARE_IMM, -1, vtable_reg, vtable);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/ir-emit.h:703:26: note: expanded from macro 'MONO_EMIT_NEW_BIALU_IMM'
        inst->inst_imm = (target_mgreg_t)(imm); \
                         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/32/parsed_console/log.html

/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/aot-runtime.c:2908:27: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                code_start = (guint8*)(((mgreg_t)code_start) & ~1);
                                        ^~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/aot-runtime.c:2979:29: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                        jei->try_start = (void*)((mgreg_t)jei->try_start & ~1);
                                                 ^~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/aot-runtime.c:2980:27: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                        jei->try_end = (void*)((mgreg_t)jei->try_end & ~1);
                                               ^~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/aot-runtime.c:2982:33: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                        jei->handler_start = (void*)((mgreg_t)jei->handler_start + 1);

4 errors generated.

warnings and errors:

/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:775:16: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                int offset = (mgreg_t)MONO_CONTEXT_GET_IP (ctx) - (mgreg_t)ji->code_start;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:775:53: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                int offset = (mgreg_t)MONO_CONTEXT_GET_IP (ctx) - (mgreg_t)ji->code_start;
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:783:13: warning: cast to 'void *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-void-pointer-cast]
                                        info = (gpointer)mono_arch_context_get_int_reg (ctx, entry->reg);
                                               ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:785:36: warning: cast to 'char *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-pointer-cast]
                                        info = *(gpointer*)(gpointer)((char*)mono_arch_context_get_int_reg (ctx, entry->reg) + entry->offset);
                                                                      ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:792:11: warning: cast to 'void *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-void-pointer-cast]
                        info = (gpointer)mono_arch_context_get_int_reg (ctx, gi->this_reg);
                               ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:794:34: warning: cast to 'char *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-pointer-cast]
                        info = *(gpointer*)(gpointer)((char*)mono_arch_context_get_int_reg (ctx, gi->this_reg) +
                                                      ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1093:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&extra_ctx, mono_walk_stack_with_ctx);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:392:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_BP ((ctx), __builtin_frame_address (0));       \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:408:68: note: expanded from macro 'MONO_CONTEXT_SET_BP'
                                                                   ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1093:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&extra_ctx, mono_walk_stack_with_ctx);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:393:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_SP ((ctx), __builtin_frame_address (0));       \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:409:68: note: expanded from macro 'MONO_CONTEXT_SET_SP'
                                                                   ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1093:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&extra_ctx, mono_walk_stack_with_ctx);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:394:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_IP ((ctx), (func));    \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:407:54: note: expanded from macro 'MONO_CONTEXT_SET_IP'
                                                     ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1218:9: warning: cast to 'void *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-void-pointer-cast]
        while (MONO_CONTEXT_GET_SP (&ctx) < jit_tls->end_of_stack) {
               ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:413:35: note: expanded from macro 'MONO_CONTEXT_GET_SP'
                                  ^
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1551:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&ctx, ves_icall_get_frame_info);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:392:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_BP ((ctx), __builtin_frame_address (0));       \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:408:68: note: expanded from macro 'MONO_CONTEXT_SET_BP'
                                                                   ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1551:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&ctx, ves_icall_get_frame_info);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:393:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_SP ((ctx), __builtin_frame_address (0));       \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:409:68: note: expanded from macro 'MONO_CONTEXT_SET_SP'
                                                                   ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1551:3: error: cast from pointer to smaller type 'mgreg_t' (aka 'int') loses information
                MONO_INIT_CONTEXT_FROM_FUNC (&ctx, ves_icall_get_frame_info);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-arm.h:394:3: note: expanded from macro 'MONO_INIT_CONTEXT_FROM_FUNC'
                MONO_CONTEXT_SET_IP ((ctx), (func));    \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/utils/mono-context.h:407:54: note: expanded from macro 'MONO_CONTEXT_SET_IP'
                                                     ^~~~~~~~~~~
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios-cxx/mono/mini/mini-exceptions.c:1991:9: warning: cast to 'void *' from smaller integer type 'mgreg_t' (aka 'int') [-Wint-to-void-pointer-cast]
                        ip = MONO_CONTEXT_GET_IP (ctx);

and more

Root of the problem:

if SIZEOF_REGISTER == 4
typedef gint32 mgreg_t;
elif SIZEOF_REGISTER == 8
typedef gint64 mgreg_t;
endif

if TARGET_SIZEOF_VOID_P == 4
typedef gint32 target_mgreg_t;
else
typedef gint64 target_mgreg_t;
endif

SIZEOF_REGISTER is about the target, but choses host mgreg_t.
So we truncate pointers in dead-ish code JIT and runtime in cross compilers.

So they can’t also run natively. Unless mgreg_t is replaced by, essentially, gssize,
though that isn't always correct for x32 and arm64_32, where gssize is like 32bits
but mgreg_t is likely 64bits. It depends on use. Often we are mixing mgreg_t
with pointers, in which case gssize is correct. Sometimes are using it for register
context, in which case it can be too small. In as much as that register context
is pointers (stack and IP and looking for GC roots, it should be ok). In as much as
it is debugger, less ok, as code going 64bit math on integers (not pointers)
in 32bit address space would use truncated data.

Introduce host_mgreg_t which is usually gssize, but not e.g. on x32 and arm64_32.
Ideally detection would be a bit better. Like maybe based on siginfo or jmpbuf.
It is not clear if pointers should be zero extended or sign extended i.e.

host_mgreg_t = (host_mgreg_t)(gsize)pointer
or
host_mgreg_t = (host_mgreg_t)(gssize)pointer

Here I have zero extended them.