Make libmono and dependencies compilables with the latest MSVC++ compiler. __var needs to be declared at the beginning of the code block, otherwise error C2275: 'guint' : illegal use of this type as an expression