Revert "Implement fast il wrapper for v4 Monitor.Enter."
This reverts commit 171e69041898f488f332c5a2fad71e40f5863c5d. The newly introduced mono_runtime_is_critical_method function
breaks pedump link as follows:

/home/src/build/mono/mono/mono/utils/mono-threads.c:385: undefined reference to `mono_runtime_is_critical_method'
/usr/bin/ld: pedump: hidden symbol `mono_runtime_is_critical_method' isn't defined
/usr/bin/ld: final link failed: Bad value