[corlib] Fix Marshal test to not rely on Assert.Less
It doesn't work on nunitlite e.g. on XA:

```
src/corlib/Test/System.Runtime.InteropServices/MarshalTest.cs(268,11): error CS0117: `NUnit.Framework.Assert' does not contain a definition for `Less'
```

(cherry picked from commit 448da87d4498a175da4d2eda233b939012e80f30)