Revert to NUnitLite:764656c
This would break on iOS with following stacktrace:

```
Unhandled Exception:
System.ArgumentException: An item with the same key has already been added. Key: MonoTouchFixtures.CoreFoundation.BundleTest.TestStaticResourceUrlsNullType
  at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException (System.Object key) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/throwhelper.cs:176
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x001ad] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:466
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:232
  at NUnit.Framework.Internal.FinallyDelegate.Set (NUnit.Framework.Internal.TestExecutionContext context, System.Int64 startTicks, NUnit.Framework.Internal.TestResult result) [0x00023] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/FinallyDelegate.cs:77
  at NUnit.Framework.Internal.WorkItems.WorkItem.DispatchWork (System.Object o) [0x00059] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:204
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
  at NUnit.Framework.Internal.WorkItems.WorkItem.RunTest () [0x00005] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:188
  at NUnit.Framework.Internal.WorkItems.WorkItem.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00063] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:136
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.RunChildren () [0x00035] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:154
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.PerformWork () [0x000de] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:93
  at NUnit.Framework.Internal.WorkItems.WorkItem.DispatchWork (System.Object o) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:205
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
  at NUnit.Framework.Internal.WorkItems.WorkItem.RunTest () [0x00005] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:188
  at NUnit.Framework.Internal.WorkItems.WorkItem.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00063] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:136
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.RunChildren () [0x00035] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:154
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.PerformWork () [0x000de] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:93
  at NUnit.Framework.Internal.WorkItems.WorkItem.DispatchWork (System.Object o) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:205
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
  at NUnit.Framework.Internal.WorkItems.WorkItem.RunTest () [0x00005] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:188
  at NUnit.Framework.Internal.WorkItems.WorkItem.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00063] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:136
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.RunChildren () [0x00035] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:154
  at NUnit.Framework.Internal.WorkItems.CompositeWorkItem.PerformWork () [0x000de] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/CompositeWorkItem.cs:93
  at NUnit.Framework.Internal.WorkItems.WorkItem.DispatchWork (System.Object o) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:205
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
  at NUnit.Framework.Internal.WorkItems.WorkItem.RunTest () [0x00005] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:188
  at NUnit.Framework.Internal.WorkItems.WorkItem.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00063] in /Users/poupou/git/d15-7/xamarin-macios/external/mono/external/nunit-lite/NUnitLite-1.0.0/src/framework/Internal/WorkItems/WorkItem.cs:136
  at MonoTouch.NUnit.UI.BaseTouchRunner.Run (NUnit.Framework.Internal.Test test) [0x0004d] in /Users/poupou/git/d15-7/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:449
  at MonoTouch.NUnit.UI.BaseTouchRunner.Run () [0x00030] in /Users/poupou/git/d15-7/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:171
  at MonoTouch.NUnit.UI.BaseTouchRunner.<AutoRun>b__40_0 () [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:139
  at MonoTouch.NUnit.UI.TouchRunner+<>c__DisplayClass19_0.<ExecuteOnMainThread>b__0 () [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/external/Touch.Unit/NUnitLite/TouchRunner/TouchRunner.cs:685
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/poupou/git/d15-7/xamarin-macios/src/Foundation/NSAction.cs:125
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/poupou/git/d15-7/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/poupou/git/d15-7/xamarin-macios/src/UIKit/UIApplication.cs:63
at monotouchtest.Application.Main (System.String[] args) [0x00011] in /Users/poupou/git/d15-7/xamarin-macios/tests/monotouch-test/Main.cs:28
```